### ISSUE TITLE
Custom headers from golang

### ISSUE THREAD

**Issue by iNDicat0r** [yunspace/serverless-golang#2] opened 2017-03-02 14:25 UTC
Hi

How can i set a custom header within the golang runtime?

Regards

**Comment by cristim** [comment] 2017-03-02 19:28
It's not yet supported by this example, I will make a pull request that adds support for it.

**Comment by iNDicat0r** [comment] 2017-03-02 21:12
Awesome, will be waiting to see it!

**Comment by cristim** [comment] 2017-03-03 07:58
I'm working on it at https://github.com/cristim/serverless-golang/tree/aws-lambda-go-shim, still not ready yet, the header is somehow lost, likely filtered by the API Gateway

**Comment by iNDicat0r** [comment] 2017-03-03 10:45
My understanding is that the lambda response to the API gateway should contain the header value. In nodejs its set using the context object, however if i understood correctly the go binary gets the event object as stdin and does return the final value of the object as the stdout.

This sounds like the context should be set within the python environment..

**Comment by cristim** [comment] 2017-03-03 17:02
@fsenart replied this and said it should work:
You have to send headers before writing the first ever byte in body
so exchange the two lines and it should be ok

**Comment by yunspace** [comment] 2017-03-13 11:58
I've merged PR #3 for now and will look at making both `lambda-go-shim` and `lambda-go-net` available in the same project in the future.

**Comment by cristim** [comment] 2017-03-15 09:17
I think this can be closed, extending the example to a multi-function configuration should be tracked in a new issue.

**Comment by yunspace** [comment] 2017-03-20 05:09
Thanks @cristim. Will close this for now if everyone is happy. Would like to explore why the `context` object doesn't work in the `go-shim` but will raise separate ticket.

**Closed by yunspace** 2017-03-20 05:09 UTC

**Comment by cristim** [comment] 2017-03-20 11:38
@fsenart, are you aware of any issues with the `context` objects?

**Comment by yunspace** [comment] 2017-03-30 13:31
hi @fsenart sorry for the confusion, the issue is to provide an example of setting custom header using `context` rather than `context` not working. My bad, I have re-phrased.

**Comment by yunspace** [comment] 2017-04-23 13:28
FYI custom headers can also be set via https://github.com/yunspace/serverless-golang/blob/master/aws/event/event_handler.go#L16
